on:
    # Manual trigger for Terraform Destroy
    workflow_dispatch:
jobs:
  destroy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.21-bookworm
    defaults:
      run:
        working-directory: ./terraform  
    # needs: terraform  # This job should only run after the terraform job
    env:
      STAGE: "dev"
      REGION: "us-east-1"
    if: ${{ github.event_name == 'workflow_dispatch' }}  # This ensures it only runs for manual dispatch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Install terraform
        run: |
            apt-get update
            apt-get install -y gnupg software-properties-common
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
            apt update
            apt-get install terraform
      # Set AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      # Run Terraform Destroy to destroy the infrastructure
      - name: Terraform Destroy
        run: |
          terraform init
          terraform destroy -auto-approve
  